# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Feb 09 11:54:17 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(992, 736)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtGui.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(730, 30, 251, 221))
        self.listView.setObjectName("listView")
        self.plotWidget = QtGui.QWidget(self.centralwidget)
        self.plotWidget.setGeometry(QtCore.QRect(280, 30, 401, 221))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setObjectName("plotWidget")
        self.plot_data_live = QtGui.QVBoxLayout(self.plotWidget)
        self.plot_data_live.setContentsMargins(0, 0, 0, 0)
        self.plot_data_live.setObjectName("plot_data_live")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 97, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.layout_checkboxes = QtGui.QVBoxLayout(self.layoutWidget)
        self.layout_checkboxes.setContentsMargins(0, 0, 0, 0)
        self.layout_checkboxes.setObjectName("layout_checkboxes")
        self.checkPIActive = QtGui.QCheckBox(self.layoutWidget)
        self.checkPIActive.setObjectName("checkPIActive")
        self.layout_checkboxes.addWidget(self.checkPIActive)
        self.checkIRon = QtGui.QCheckBox(self.layoutWidget)
        self.checkIRon.setObjectName("checkIRon")
        self.layout_checkboxes.addWidget(self.checkIRon)
        self.checkGreenon = QtGui.QCheckBox(self.layoutWidget)
        self.checkGreenon.setObjectName("checkGreenon")
        self.layout_checkboxes.addWidget(self.checkGreenon)
        self.sliderPosition = QtGui.QSlider(self.centralwidget)
        self.sliderPosition.setGeometry(QtCore.QRect(30, 240, 160, 19))
        self.sliderPosition.setMaximum(600)
        self.sliderPosition.setSliderPosition(300)
        self.sliderPosition.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPosition.setObjectName("sliderPosition")
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(350, 260, 335, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_to_zero = QtGui.QPushButton(self.layoutWidget1)
        self.btn_to_zero.setObjectName("btn_to_zero")
        self.horizontalLayout.addWidget(self.btn_to_zero)
        self.btn_stop_record = QtGui.QPushButton(self.layoutWidget1)
        self.btn_stop_record.setObjectName("btn_stop_record")
        self.horizontalLayout.addWidget(self.btn_stop_record)
        self.btn_clear_record = QtGui.QPushButton(self.layoutWidget1)
        self.btn_clear_record.setObjectName("btn_clear_record")
        self.horizontalLayout.addWidget(self.btn_clear_record)
        self.btn_start_record = QtGui.QPushButton(self.layoutWidget1)
        self.btn_start_record.setObjectName("btn_start_record")
        self.horizontalLayout.addWidget(self.btn_start_record)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(300, 310, 411, 301))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.plotWidget_timetrace = QtGui.QWidget(self.tab)
        self.plotWidget_timetrace.setGeometry(QtCore.QRect(0, 10, 401, 241))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget_timetrace.sizePolicy().hasHeightForWidth())
        self.plotWidget_timetrace.setSizePolicy(sizePolicy)
        self.plotWidget_timetrace.setObjectName("plotWidget_timetrace")
        self.plot_data_timetrace = QtGui.QVBoxLayout(self.plotWidget_timetrace)
        self.plot_data_timetrace.setContentsMargins(0, 0, 0, 0)
        self.plot_data_timetrace.setObjectName("plot_data_timetrace")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.plotWidget_psd = QtGui.QWidget(self.tab_2)
        self.plotWidget_psd.setGeometry(QtCore.QRect(0, 0, 401, 271))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget_psd.sizePolicy().hasHeightForWidth())
        self.plotWidget_psd.setSizePolicy(sizePolicy)
        self.plotWidget_psd.setObjectName("plotWidget_psd")
        self.plot_data_psd = QtGui.QVBoxLayout(self.plotWidget_psd)
        self.plot_data_psd.setContentsMargins(0, 0, 0, 0)
        self.plot_data_psd.setObjectName("plot_data_psd")
        self.tabWidget.addTab(self.tab_2, "")
        self.treeWidget = QtGui.QTreeWidget(self.centralwidget)
        self.treeWidget.setEnabled(True)
        self.treeWidget.setGeometry(QtCore.QRect(20, 310, 261, 301))
        self.treeWidget.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setObjectName("treeWidget")
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(440, 620, 171, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.btn_start_record_fpga_2 = QtGui.QPushButton(self.centralwidget)
        self.btn_start_record_fpga_2.setGeometry(QtCore.QRect(610, 620, 91, 23))
        self.btn_start_record_fpga_2.setObjectName("btn_start_record_fpga_2")
        self.btn_start_record_fpga = QtGui.QPushButton(self.centralwidget)
        self.btn_start_record_fpga.setGeometry(QtCore.QRect(300, 620, 131, 23))
        self.btn_start_record_fpga.setObjectName("btn_start_record_fpga")
        self.btn_minus = QtGui.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(40, 260, 21, 23))
        self.btn_minus.setObjectName("btn_minus")
        self.btn_center = QtGui.QPushButton(self.centralwidget)
        self.btn_center.setGeometry(QtCore.QRect(100, 260, 21, 23))
        self.btn_center.setObjectName("btn_center")
        self.lbl_detector_signal = QtGui.QLabel(self.centralwidget)
        self.lbl_detector_signal.setGeometry(QtCore.QRect(280, 260, 47, 13))
        self.lbl_detector_signal.setObjectName("lbl_detector_signal")
        self.lbl_pol_position = QtGui.QLabel(self.centralwidget)
        self.lbl_pol_position.setGeometry(QtCore.QRect(200, 240, 47, 13))
        self.lbl_pol_position.setObjectName("lbl_pol_position")
        self.btn_plus = QtGui.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(160, 260, 21, 23))
        self.btn_plus.setObjectName("btn_plus")
        self.cmb_filterwheel = QtGui.QComboBox(self.centralwidget)
        self.cmb_filterwheel.setGeometry(QtCore.QRect(110, 20, 69, 22))
        self.cmb_filterwheel.setObjectName("cmb_filterwheel")
        self.tree_settings = QtGui.QWidget(self.centralwidget)
        self.tree_settings.setGeometry(QtCore.QRect(720, 310, 221, 281))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_settings.sizePolicy().hasHeightForWidth())
        self.tree_settings.setSizePolicy(sizePolicy)
        self.tree_settings.setObjectName("tree_settings")
        self.settings = QtGui.QVBoxLayout(self.tree_settings)
        self.settings.setContentsMargins(0, 0, 0, 0)
        self.settings.setObjectName("settings")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 992, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.checkPIActive.setText(QtGui.QApplication.translate("MainWindow", "PI - loop active", None, QtGui.QApplication.UnicodeUTF8))
        self.checkIRon.setText(QtGui.QApplication.translate("MainWindow", "IR on", None, QtGui.QApplication.UnicodeUTF8))
        self.checkGreenon.setText(QtGui.QApplication.translate("MainWindow", "Green on", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_to_zero.setText(QtGui.QApplication.translate("MainWindow", "bring pol. to zero", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_stop_record.setText(QtGui.QApplication.translate("MainWindow", "stop", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear_record.setText(QtGui.QApplication.translate("MainWindow", "clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_start_record.setText(QtGui.QApplication.translate("MainWindow", "Record Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "TimeTrace", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_start_record_fpga_2.setText(QtGui.QApplication.translate("MainWindow", "Save to disk", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_start_record_fpga.setText(QtGui.QApplication.translate("MainWindow", "Record Data (FPGA)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_minus.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_center.setText(QtGui.QApplication.translate("MainWindow", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_detector_signal.setText(QtGui.QApplication.translate("MainWindow", "Det.Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_pol_position.setText(QtGui.QApplication.translate("MainWindow", "Pol.Pos", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_plus.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))

