# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic_application_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1373, 849)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 220, 721, 421))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_scripts = QtGui.QWidget()
        self.tab_scripts.setObjectName(_fromUtf8("tab_scripts"))
        self.tree_scripts = QtGui.QTreeWidget(self.tab_scripts)
        self.tree_scripts.setEnabled(True)
        self.tree_scripts.setGeometry(QtCore.QRect(0, 40, 711, 301))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_scripts.sizePolicy().hasHeightForWidth())
        self.tree_scripts.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tree_scripts.setFont(font)
        self.tree_scripts.setAutoFillBackground(False)
        self.tree_scripts.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.tree_scripts.setAlternatingRowColors(True)
        self.tree_scripts.setWordWrap(True)
        self.tree_scripts.setHeaderHidden(False)
        self.tree_scripts.setObjectName(_fromUtf8("tree_scripts"))
        self.tree_scripts.header().setDefaultSectionSize(150)
        self.tree_scripts.header().setHighlightSections(True)
        self.progressBar = QtGui.QProgressBar(self.tab_scripts)
        self.progressBar.setGeometry(QtCore.QRect(230, 352, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.btn_stop_script = QtGui.QPushButton(self.tab_scripts)
        self.btn_stop_script.setGeometry(QtCore.QRect(120, 352, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_stop_script.setFont(font)
        self.btn_stop_script.setObjectName(_fromUtf8("btn_stop_script"))
        self.btn_start_script = QtGui.QPushButton(self.tab_scripts)
        self.btn_start_script.setGeometry(QtCore.QRect(10, 352, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_start_script.setFont(font)
        self.btn_start_script.setObjectName(_fromUtf8("btn_start_script"))
        self.btn_plot_script = QtGui.QPushButton(self.tab_scripts)
        self.btn_plot_script.setGeometry(QtCore.QRect(0, 2, 101, 31))
        self.btn_plot_script.setObjectName(_fromUtf8("btn_plot_script"))
        self.btn_load_scripts = QtGui.QPushButton(self.tab_scripts)
        self.btn_load_scripts.setGeometry(QtCore.QRect(550, 10, 151, 23))
        self.btn_load_scripts.setObjectName(_fromUtf8("btn_load_scripts"))
        self.btn_save_script_data = QtGui.QPushButton(self.tab_scripts)
        self.btn_save_script_data.setGeometry(QtCore.QRect(390, 10, 151, 23))
        self.btn_save_script_data.setObjectName(_fromUtf8("btn_save_script_data"))
        self.tree_scripts.raise_()
        self.progressBar.raise_()
        self.btn_stop_script.raise_()
        self.btn_plot_script.raise_()
        self.btn_load_scripts.raise_()
        self.btn_start_script.raise_()
        self.btn_save_script_data.raise_()
        self.tabWidget.addTab(self.tab_scripts, _fromUtf8(""))
        self.tab_monitor = QtGui.QWidget()
        self.tab_monitor.setObjectName(_fromUtf8("tab_monitor"))
        self.tree_monitor = QtGui.QTreeWidget(self.tab_monitor)
        self.tree_monitor.setEnabled(True)
        self.tree_monitor.setGeometry(QtCore.QRect(0, 30, 711, 431))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_monitor.sizePolicy().hasHeightForWidth())
        self.tree_monitor.setSizePolicy(sizePolicy)
        self.tree_monitor.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.tree_monitor.setHeaderHidden(False)
        self.tree_monitor.setObjectName(_fromUtf8("tree_monitor"))
        self.tree_monitor.header().setDefaultSectionSize(150)
        self.tree_monitor.header().setHighlightSections(True)
        self.btn_plot_probe = QtGui.QPushButton(self.tab_monitor)
        self.btn_plot_probe.setGeometry(QtCore.QRect(0, 2, 101, 23))
        self.btn_plot_probe.setObjectName(_fromUtf8("btn_plot_probe"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_monitor)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 0, 591, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lbl_probe_log_path = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_probe_log_path.setObjectName(_fromUtf8("lbl_probe_log_path"))
        self.horizontalLayout.addWidget(self.lbl_probe_log_path)
        self.txt_probe_log_path = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.txt_probe_log_path.setObjectName(_fromUtf8("txt_probe_log_path"))
        self.horizontalLayout.addWidget(self.txt_probe_log_path)
        self.chk_probe_log = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chk_probe_log.setObjectName(_fromUtf8("chk_probe_log"))
        self.horizontalLayout.addWidget(self.chk_probe_log)
        self.tabWidget.addTab(self.tab_monitor, _fromUtf8(""))
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setObjectName(_fromUtf8("tab_settings"))
        self.tree_settings = QtGui.QTreeWidget(self.tab_settings)
        self.tree_settings.setEnabled(True)
        self.tree_settings.setGeometry(QtCore.QRect(0, 30, 711, 401))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_settings.sizePolicy().hasHeightForWidth())
        self.tree_settings.setSizePolicy(sizePolicy)
        self.tree_settings.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.tree_settings.setHeaderHidden(False)
        self.tree_settings.setObjectName(_fromUtf8("tree_settings"))
        self.tree_settings.header().setDefaultSectionSize(150)
        self.tree_settings.header().setHighlightSections(True)
        self.btn_load_instruments = QtGui.QPushButton(self.tab_settings)
        self.btn_load_instruments.setGeometry(QtCore.QRect(540, 0, 161, 23))
        self.btn_load_instruments.setObjectName(_fromUtf8("btn_load_instruments"))
        self.tabWidget.addTab(self.tab_settings, _fromUtf8(""))
        self.matplotlibwidget = MatplotlibWidget(self.centralwidget)
        self.matplotlibwidget.setGeometry(QtCore.QRect(740, 0, 621, 691))
        self.matplotlibwidget.setObjectName(_fromUtf8("matplotlibwidget"))
        self.matplotlibwidget_2 = MatplotlibWidget(self.centralwidget)
        self.matplotlibwidget_2.setGeometry(QtCore.QRect(10, 0, 391, 211))
        self.matplotlibwidget_2.setObjectName(_fromUtf8("matplotlibwidget_2"))
        self.btn_save_gui = QtGui.QPushButton(self.centralwidget)
        self.btn_save_gui.setGeometry(QtCore.QRect(1130, 750, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_save_gui.setFont(font)
        self.btn_save_gui.setObjectName(_fromUtf8("btn_save_gui"))
        self.btn_load_gui = QtGui.QPushButton(self.centralwidget)
        self.btn_load_gui.setGeometry(QtCore.QRect(1050, 750, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_load_gui.setFont(font)
        self.btn_load_gui.setObjectName(_fromUtf8("btn_load_gui"))
        self.list_history = QtGui.QListView(self.centralwidget)
        self.list_history.setGeometry(QtCore.QRect(0, 670, 721, 131))
        self.list_history.setObjectName(_fromUtf8("list_history"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 640, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(500, 0, 104, 31))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1373, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tree_scripts.headerItem().setText(0, _translate("MainWindow", "Parameter/Script", None))
        self.tree_scripts.headerItem().setText(1, _translate("MainWindow", "Value", None))
        self.btn_stop_script.setText(_translate("MainWindow", "stop", None))
        self.btn_start_script.setText(_translate("MainWindow", "start", None))
        self.btn_plot_script.setText(_translate("MainWindow", "plot script  ↑", None))
        self.btn_load_scripts.setText(_translate("MainWindow", "import script", None))
        self.btn_save_script_data.setText(_translate("MainWindow", "save script data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_scripts), _translate("MainWindow", "Scripts", None))
        self.tree_monitor.headerItem().setText(0, _translate("MainWindow", "Parameter", None))
        self.tree_monitor.headerItem().setText(1, _translate("MainWindow", "Value", None))
        self.btn_plot_probe.setText(_translate("MainWindow", "plot probe  ↑", None))
        self.lbl_probe_log_path.setText(_translate("MainWindow", "Path", None))
        self.txt_probe_log_path.setText(_translate("MainWindow", "Z:\\Lab\\Cantilever\\Measurements", None))
        self.chk_probe_log.setText(_translate("MainWindow", "logging on", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_monitor), _translate("MainWindow", "Monitor", None))
        self.tree_settings.headerItem().setText(0, _translate("MainWindow", "Instrument", None))
        self.tree_settings.headerItem().setText(1, _translate("MainWindow", "Value", None))
        self.btn_load_instruments.setText(_translate("MainWindow", "import instrument", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), _translate("MainWindow", "Instruments", None))
        self.btn_save_gui.setText(_translate("MainWindow", "Save", None))
        self.btn_load_gui.setText(_translate("MainWindow", "Load", None))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "History", None))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">B26 Lab GUI</span></p></body></html>", None))

from matplotlibwidget import MatplotlibWidget
