/*
 * FPGA Interface C API example for GCC for computers running Linux.
 *
 * NOTE: In order to run this example, you must compile a LabVIEW FPGA bitfile
 *       and generate a C API for it. For more information about using this
 *       example, refer to the Examples topic of the FPGA Interface C API Help,
 *       located under
 *       Start>>All Programs>>National Instruments>>FPGA Interface C API.
 */
 
#include "NiFpga_GalvoScan.h"

#include <stdio.h>
#include <stdlib.h>

// overwrite the definition of the header file created by Labview because FPGA bitcode will be located in the subdir lib
// #define "NiFpga_GalvoScan.lvbitx" 

/*
IMPORTANT need to replace

#define NiFpga_GalvoScan_Bitfile "NiFpga_GalvoScan.lvbitx" 

with

#define NiFpga_GalvoScan_Bitfile "C:\\Users\\Experiment\\PycharmProjects\\PythonLab\\src\\labview_fpga_lib\\galvo_scan\\NiFpga_GalvoScan.lvbitx" 

in NiFpga_FPGA_GalvoScan.h (which is generated by labview C API)

*/

void start_fpga(NiFpga_Session* session, NiFpga_Status* status)
{
	// must be called before any other calls 
	*status = NiFpga_Initialize();
	printf("initializing FPGA Galvo Scan \n");
	printf("bitfile expected at:\n");
	printf(NiFpga_GalvoScan_Bitfile);
	printf("\n");
	
	if (NiFpga_IsNotError(*status))
	{
		// opens a session, downloads the bitstream, and runs the FPGA 
		NiFpga_MergeStatus(status, NiFpga_Open(NiFpga_GalvoScan_Bitfile,
												NiFpga_GalvoScan_Signature,
												"RIO0",
												NiFpga_OpenAttribute_NoRun,
												session));
												
		// reset
		NiFpga_MergeStatus(status, NiFpga_Reset(*session));
		
		if (NiFpga_IsNotError(*status))
		{
			// run the FPGA application 
			NiFpga_MergeStatus(status, NiFpga_Run(*session, 0));
		}
		else{
			// print warning
			printf("error occurred at FPGA open");
			printf("%d", *status);
			
		}
	}
	
	fflush(stdout);
	
}

void stop_fpga(NiFpga_Session* session, NiFpga_Status* status)
{
	// close the session now that we're done 
	NiFpga_MergeStatus(status, NiFpga_Close(*session, 0));

	// must be called after all other calls 
	NiFpga_MergeStatus(status, NiFpga_Finalize());
}

void reset_fpga(NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_Reset(*session));
}

// read logical indicators
_Bool read_DMATimeOut(NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_Bool state;
	NiFpga_MergeStatus(status, NiFpga_ReadBool(*session,NiFpga_GalvoScan_IndicatorBool_DMAtimeout,&state));
	return state;
}
_Bool read_running(NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_Bool state;
	NiFpga_MergeStatus(status, NiFpga_ReadBool(*session,NiFpga_GalvoScan_IndicatorBool_running,&state));
	return state;
}
_Bool read_output_valid(NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_Bool state;
	NiFpga_MergeStatus(status, NiFpga_ReadBool(*session,NiFpga_GalvoScan_IndicatorBool_outputvalid,&state));
	return state;
}
// set logical values
void set_acquire(_Bool state, NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_WriteBool(*session,NiFpga_GalvoScan_ControlBool_acquire, state));
}
_Bool read_acquire(NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_Bool state;
	NiFpga_MergeStatus(status, NiFpga_ReadBool(*session,NiFpga_GalvoScan_ControlBool_acquire,&state));
	return state;
}
void set_abort(_Bool state, NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_WriteBool(*session,NiFpga_GalvoScan_ControlBool_abort, state));
}
_Bool read_abort(NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_Bool state;
	NiFpga_MergeStatus(status, NiFpga_ReadBool(*session,NiFpga_GalvoScan_ControlBool_abort,&state));
	return state;
}

// read value
uint32_t read_loop_time(NiFpga_Session* session, NiFpga_Status* status)
{
	uint32_t value;

	NiFpga_MergeStatus(status, NiFpga_ReadU32(*session,NiFpga_GalvoScan_IndicatorU32_loop_time,&value));
	return value;
}

uint32_t read_DMA_elem_to_write(NiFpga_Session* session, NiFpga_Status* status)
{
	uint32_t value;

	NiFpga_MergeStatus(status, NiFpga_ReadU32(*session,NiFpga_GalvoScan_IndicatorU32_DMA_elem_to_write,&value));
	return value;
}


// set parameters
void set_Nx(int16_t value, NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_WriteI16(*session,NiFpga_GalvoScan_ControlI16_N_x,value));
}
int16_t read_Nx(NiFpga_Session* session, NiFpga_Status* status)
{
	int16_t value;

	NiFpga_MergeStatus(status, NiFpga_ReadI16(*session,NiFpga_GalvoScan_ControlI16_N_x,&value));
	return value;
}

void set_Vmin_x(int16_t value, NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_WriteI16(*session,NiFpga_GalvoScan_ControlI16_Vmin_x,value));
}

void set_dVmin_x(int16_t value, NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_WriteI16(*session,NiFpga_GalvoScan_ControlI16_dVmin_x,value));
}

void set_Ny(int16_t value, NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_WriteI16(*session,NiFpga_GalvoScan_ControlI16_N_y,value));
}
int16_t read_Ny(NiFpga_Session* session, NiFpga_Status* status)
{
	int16_t value;

	NiFpga_MergeStatus(status, NiFpga_ReadI16(*session,NiFpga_GalvoScan_ControlI16_N_y,&value));
	return value;
}

void set_Vmin_y(int16_t value, NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_WriteI16(*session,NiFpga_GalvoScan_ControlI16_Vmin_y,value));
}

void set_dVmin_y(int16_t value, NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_WriteI16(*session,NiFpga_GalvoScan_ControlI16_dVmin_y,value));
}

void set_scanmode_x(uint8_t value, NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_WriteU8(*session,NiFpga_GalvoScan_ControlU8_scanmodex,value));
}

void set_scanmode_y(uint8_t value, NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_WriteU8(*session,NiFpga_GalvoScan_ControlU8_scanmodey,value));
}

void set_detector_mode(uint8_t value, NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_WriteU8(*session,NiFpga_GalvoScan_ControlU8_detector_mode,value));
}



void set_settle_time(uint16_t value, NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_WriteU16(*session,NiFpga_GalvoScan_ControlU16_settle_time_us,value));
}
uint16_t read_settle_time(NiFpga_Session* session, NiFpga_Status* status)
{
	uint16_t value;
	NiFpga_MergeStatus(status, NiFpga_ReadU16(*session,NiFpga_GalvoScan_ControlU16_settle_time_us,&value));
	return value;
}

void set_meas_per_pt(uint8_t value, NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_WriteU8(*session,NiFpga_GalvoScan_ControlU8_measurements_per_pt,value));
}
uint8_t read_meas_per_pt(NiFpga_Session* session, NiFpga_Status* status)
{
	uint8_t value;
	NiFpga_MergeStatus(status, NiFpga_ReadU8(*session,NiFpga_GalvoScan_ControlU8_measurements_per_pt,&value));
	return value;
}

void set_piezo_voltage(int16_t value, NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_WriteI16(*session,NiFpga_GalvoScan_ControlI16_Connector1AO2,value));
}
// read parameters
int32_t read_i(NiFpga_Session* session, NiFpga_Status* status)
{
	int32_t value;

	NiFpga_MergeStatus(status, NiFpga_ReadI32(*session,NiFpga_GalvoScan_IndicatorI32_i,&value));
	return value;
}

int32_t read_elements_written_to_dma(NiFpga_Session* session, NiFpga_Status* status)
{
	int32_t value;

	NiFpga_MergeStatus(status, NiFpga_ReadI32(*session,NiFpga_GalvoScan_IndicatorI32_datasenttoDMA,&value));
	return value;
}

int16_t read_detector_signal(NiFpga_Session* session, NiFpga_Status* status)
{
	int16_t value;

	NiFpga_MergeStatus(status, NiFpga_ReadI16(*session,NiFpga_GalvoScan_IndicatorI16_Detectorsignal,&value));
	return value;
}

int32_t read_ix(NiFpga_Session* session, NiFpga_Status* status)
{
	int32_t value;

	NiFpga_MergeStatus(status, NiFpga_ReadI32(*session,NiFpga_GalvoScan_IndicatorI32_ix,&value));
	return value;
}

int32_t read_iy(NiFpga_Session* session, NiFpga_Status* status)
{
	int32_t value;

	NiFpga_MergeStatus(status, NiFpga_ReadI32(*session,NiFpga_GalvoScan_IndicatorI32_iy,&value));
	return value;
}

int32_t read_failed(NiFpga_Session* session, NiFpga_Status* status)
{
	int32_t value;

	NiFpga_MergeStatus(status, NiFpga_ReadI32(*session,NiFpga_GalvoScan_IndicatorI32_failed,&value));
	return value;
}


// =========================================================
// ============ FIFO =======================================
// =========================================================
size_t configure_FIFO(size_t requestedDepth, NiFpga_Session* session, NiFpga_Status* status)
{
	size_t actualDepth;
	NiFpga_MergeStatus(status, NiFpga_ConfigureFifo2(*session, NiFpga_GalvoScan_TargetToHostFifoI16_DMA, requestedDepth, &actualDepth));
	return actualDepth;
}

void start_FIFO(NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_StartFifo(*session, NiFpga_GalvoScan_TargetToHostFifoI16_DMA));
}

void stop_FIFO(NiFpga_Session* session, NiFpga_Status* status)
{
	NiFpga_MergeStatus(status, NiFpga_StopFifo(*session, NiFpga_GalvoScan_TargetToHostFifoI16_DMA));
}


void read_FIFO(int16_t* input, size_t size, NiFpga_Session* session, NiFpga_Status* status,size_t* elementsRemaining)
{
	/* copy FIFO data from the FPGA */
	NiFpga_MergeStatus(status,
					   NiFpga_ReadFifoI16(*session,
							   	   	   	  NiFpga_GalvoScan_TargetToHostFifoI16_DMA,
										  input,
										  size,
										  NiFpga_InfiniteTimeout,
										  elementsRemaining));
}


