# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zi_control.ui'
#
# Created: Mon Mar 21 12:23:01 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1138, 859)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_records = QtGui.QListView(self.centralwidget)
        self.list_records.setGeometry(QtCore.QRect(740, 290, 391, 141))
        self.list_records.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.list_records.setModelColumn(0)
        self.list_records.setObjectName("list_records")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(730, 500, 411, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_tag = QtGui.QLineEdit(self.layoutWidget)
        self.txt_tag.setObjectName("txt_tag")
        self.horizontalLayout_2.addWidget(self.txt_tag)
        self.btn_clear_record = QtGui.QPushButton(self.layoutWidget)
        self.btn_clear_record.setObjectName("btn_clear_record")
        self.horizontalLayout_2.addWidget(self.btn_clear_record)
        self.btn_save_record_to_disk = QtGui.QPushButton(self.layoutWidget)
        self.btn_save_record_to_disk.setObjectName("btn_save_record_to_disk")
        self.horizontalLayout_2.addWidget(self.btn_save_record_to_disk)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 340, 721, 471))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_scripts = QtGui.QWidget()
        self.tab_scripts.setObjectName("tab_scripts")
        self.tree_scripts = QtGui.QTreeWidget(self.tab_scripts)
        self.tree_scripts.setEnabled(True)
        self.tree_scripts.setGeometry(QtCore.QRect(0, 10, 711, 291))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_scripts.sizePolicy().hasHeightForWidth())
        self.tree_scripts.setSizePolicy(sizePolicy)
        self.tree_scripts.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.tree_scripts.setHeaderHidden(False)
        self.tree_scripts.setObjectName("tree_scripts")
        self.tree_scripts.header().setDefaultSectionSize(150)
        self.tree_scripts.header().setHighlightSections(True)
        self.progressBar = QtGui.QProgressBar(self.tab_scripts)
        self.progressBar.setGeometry(QtCore.QRect(230, 410, 471, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.btn_stop_script = QtGui.QPushButton(self.tab_scripts)
        self.btn_stop_script.setGeometry(QtCore.QRect(120, 410, 101, 23))
        self.btn_stop_script.setObjectName("btn_stop_script")
        self.btn_start_script = QtGui.QPushButton(self.tab_scripts)
        self.btn_start_script.setGeometry(QtCore.QRect(20, 410, 101, 23))
        self.btn_start_script.setObjectName("btn_start_script")
        self.list_scripts = QtGui.QListView(self.tab_scripts)
        self.list_scripts.setGeometry(QtCore.QRect(0, 320, 711, 61))
        self.list_scripts.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.list_scripts.setModelColumn(0)
        self.list_scripts.setObjectName("list_scripts")
        self.tabWidget.addTab(self.tab_scripts, "")
        self.tab_monitor = QtGui.QWidget()
        self.tab_monitor.setObjectName("tab_monitor")
        self.tree_monitor = QtGui.QTreeWidget(self.tab_monitor)
        self.tree_monitor.setEnabled(True)
        self.tree_monitor.setGeometry(QtCore.QRect(0, 10, 711, 431))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_monitor.sizePolicy().hasHeightForWidth())
        self.tree_monitor.setSizePolicy(sizePolicy)
        self.tree_monitor.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.tree_monitor.setHeaderHidden(False)
        self.tree_monitor.setObjectName("tree_monitor")
        self.tree_monitor.header().setDefaultSectionSize(150)
        self.tree_monitor.header().setHighlightSections(True)
        self.tabWidget.addTab(self.tab_monitor, "")
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.tree_settings = QtGui.QTreeWidget(self.tab_settings)
        self.tree_settings.setEnabled(True)
        self.tree_settings.setGeometry(QtCore.QRect(0, 10, 711, 431))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_settings.sizePolicy().hasHeightForWidth())
        self.tree_settings.setSizePolicy(sizePolicy)
        self.tree_settings.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.tree_settings.setHeaderHidden(False)
        self.tree_settings.setObjectName("tree_settings")
        self.tree_settings.header().setDefaultSectionSize(150)
        self.tree_settings.header().setHighlightSections(True)
        self.tabWidget.addTab(self.tab_settings, "")
        self.tab_history = QtGui.QWidget()
        self.tab_history.setObjectName("tab_history")
        self.tabWidget.addTab(self.tab_history, "")
        self.matplotlibwidget = MatplotlibWidget(self.centralwidget)
        self.matplotlibwidget.setGeometry(QtCore.QRect(30, 20, 400, 300))
        self.matplotlibwidget.setObjectName("matplotlibwidget")
        self.list_history = QtGui.QListView(self.centralwidget)
        self.list_history.setGeometry(QtCore.QRect(470, 10, 631, 211))
        self.list_history.setObjectName("list_history")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1138, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_tag.setText(QtGui.QApplication.translate("MainWindow", "some tag", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear_record.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_save_record_to_disk.setText(QtGui.QApplication.translate("MainWindow", "Save to disk", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_scripts.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Parameter/Script", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_scripts.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_stop_script.setText(QtGui.QApplication.translate("MainWindow", "stop", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_start_script.setText(QtGui.QApplication.translate("MainWindow", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_scripts), QtGui.QApplication.translate("MainWindow", "Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_monitor.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_monitor.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_monitor), QtGui.QApplication.translate("MainWindow", "Monitor", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_settings.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Instrument", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_settings.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_history), QtGui.QApplication.translate("MainWindow", "History", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
